server:
  port: 8080
ezdev:
  security:
    logout-default-url: http://locaihost/

spring:
  session:
    store-type: redis
  redis:
    host: 192.168.1.225
    port: 6379
    database: 0
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms